name: eksctl-windows
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
 windows:
    runs-on: windows-2019
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Install
        run: |
          choco install eksctl
          $version = eksctl info
          return "$version"
          if ($version -ne "0.110") {
           write-host "Eksctl is not the lastest version. Please update"
            } 
      - name: test
        run: |
          $version = eksctl info
          return "$version"
          if ($version -ne "0.111") {
           write-host "Eksctl is not the lastest version. Please update"
            } 
