name: eksctl-macos
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
 MacOS:
    runs-on: macos-12
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Install
        run: |
          brew install weaveworks/tap/eksctl
      - name: Version
        run: |
          eksctl version
          
